#:import ZBarCam kivy_garden.zbarcam.ZBarCam

<HomeScreen>:
	name: 'home_screen'
	Widget:
		canvas:
			Color:
				rgba: rgba('#E1E1E1')
			Rectangle:
				size: self.size
				pos: self.pos
	MDLabel:
		id: scanned_name
		# size_hint_x: 1
		text: ''.join([str(symbol.data.decode("UTF-8")) for symbol in qrcodecam.symbols])
		text2: ''.join([str(symbol.data) for symbol in qrcodecam.symbols])
		markup: True
		font_size: '10dp'
		theme_text_color: 'Custom'
		text_color: rgba('#E1E1E1')
		# halign: 'center'
		# pos_hint: {'center_y': 3, 'center_x': 0}
		on_text: root.save_scanned()
    FloatLayout:
		pos_hint: {'center_y': 0.5, 'center_x': 0.65}
		size_hint: 0.50, 0.90
		canvas:
			Color:
				rgba: rgba('#07575B')
			RoundedRectangle:
                radius: [40,40,40,40]
				size: self.size
				pos: self.pos
		MDLabel:
			text: ('[font=Fonts/Roboto-Black]STUDENT NAME[/font]')
			font_size: '15dp'
			markup: True
			halign: "left"
			theme_text_color: 'Custom'
			text_color: rgba('#FFFFFF')
			pos_hint: {'center_x': 0.55, 'center_y' : 0.9}
		FloatLayout:
			pos_hint: {'center_x': 0.5, 'center_y': 0.78}
			size_hint: 0.90, 0.15
			canvas:
				Color:
					rgba: rgba('#FFFFFF')
				RoundedRectangle:
					radius: [30,30,30,30]
					size: self.size
					pos: self.pos
			MDLabel:
				text: '[font=Fonts/Roboto-Black]' + root.student_name + '[/font]'
				font_size: '19dp'
				markup: True
				halign: "center"
				theme_text_color: 'Custom'
				text_color: rgba('#07575B')
				pos_hint: {'center_x': 0.5, 'center_y' : 0.5}
		MDLabel:
			text: ('[font=Fonts/Roboto-Black]COURSE AND SECTION[/font]')
			font_size: '15dp'
			markup: True
			halign: "left"
			theme_text_color: 'Custom'
			text_color: rgba('#FFFFFF')
			pos_hint: {'center_x': 0.55, 'center_y' : 0.65}
		FloatLayout:
			pos_hint: {'center_x': 0.5, 'center_y': 0.53}
			size_hint: 0.90, 0.15
			canvas:
				Color:
					rgba: rgba('#FFFFFF')
				RoundedRectangle:
					radius: [30,30,30,30]
					size: self.size
					pos: self.pos
			MDLabel:
				text: '[font=Fonts/Roboto-Black]' + root.student_cs + '[/font]'
				font_size: '19dp'
				markup: True
				halign: "center"
				theme_text_color: 'Custom'
				text_color: rgba('#07575B')
				pos_hint: {'center_x': 0.5, 'center_y' : 0.5}
		MDLabel:
			text: ('[font=Fonts/Roboto-Medium]' + root.qr_day + '[/font]')
			font_size: '15dp'
			markup: True
			halign: "center"
			theme_text_color: 'Custom'
			text_color: rgba('#FFFFFF')
			pos_hint: {'center_x': 0.5, 'center_y' : 0.4}
		FloatLayout:
			pos_hint: {'center_x': 0.5, 'center_y': 0.29}
			size_hint: 0.004, 0.15
			canvas:
				Color:
					rgba: rgba('#FFFFFF')
				Rectangle:
					size: self.size
					pos: self.pos
		FloatLayout:
			pos_hint: {'center_x': 0.35, 'center_y': 0.31}
			size_hint: 0.15, 0.05
			canvas:
				Color:
					rgba: rgba('#FFFFFF')
				RoundedRectangle:
					radius: [20,20,20,20]
					size: self.size
					pos: self.pos
		MDLabel:
			text: ('[font=Fonts/Roboto-Bold]Time In[/font]')
			font_size: '13dp'
			markup: True
			halign: "center"
			theme_text_color: 'Custom'
			text_color: rgba('#07575B')
			pos_hint: {'center_x': 0.35, 'center_y' : 0.31}
		MDLabel:
			text: '[font=Fonts/Roboto-Medium]' + root.time_in + '[/font]'
			font_size: '15dp'
			markup: True
			halign: "center"
			theme_text_color: 'Custom'
			text_color: rgba('#FFFFFF')
			pos_hint: {'center_x': 0.35, 'center_y' : 0.26}
		FloatLayout:
			pos_hint: {'center_x': 0.65, 'center_y': 0.31}
			size_hint: 0.15, 0.05
			canvas:
				Color:
					rgba: rgba('#FFFFFF')
				RoundedRectangle:
					radius: [20,20,20,20]
					size: self.size
					pos: self.pos
		MDLabel:
			text: ('[font=Fonts/Roboto-Bold]Time Out[/font]')
			font_size: '13dp'
			markup: True
			halign: "center"
			theme_text_color: 'Custom'
			text_color: rgba('#07575B')
			pos_hint: {'center_x': 0.65, 'center_y' : 0.31}
		MDLabel:
			text: '[font=Fonts/Roboto-Medium]' + root.time_out + '[/font]'
			font_size: '15dp'
			markup: True
			halign: "center"
			theme_text_color: 'Custom'
			text_color: rgba('#FFFFFF')
			pos_hint: {'center_x': 0.65, 'center_y' : 0.26}
		MDLabel:
			text: ('[font=Fonts/Roboto-Black]TEMPERATURE[/font]')
			font_size: '15dp'
			markup: True
			halign: "center"
			theme_text_color: 'Custom'
			text_color: rgba('#FFFFFF')
			pos_hint: {'center_x': 0.5, 'center_y' : 0.18}
		MDLabel:
			text: '[font=Fonts/Roboto-Black]' + root.student_temperature + '°C' + '[/font]'
			font_size: '21dp'
			markup: True
			halign: "center"
			theme_text_color: 'Custom'
			text_color: rgba('#FFFFFF')
			pos_hint: {'center_x': 0.5, 'center_y' : 0.125}
    FloatLayout:
		pos_hint: {'center_y': 0.74, 'center_x': 0.2}
		size_hint: 0.20, 0.40
		canvas:
			Color:
				rgba: rgba('#61A4AD')
			RoundedRectangle:
                radius: [40,40,40,40]
				size: self.size
				pos: self.pos
		FloatLayout:
			pos_hint: {'center_y': 0.5, 'center_x': 0.5}
			size_hint: 0.90, 0.90
			canvas:
				Color:
					rgba: rgba('#FFFFFF')
				RoundedRectangle:
					radius: [40,40,40,40]
					size: self.size
					pos: self.pos
			FitImage:
				pos_hint: {'center_x': 0.5, 'center_y' : 0.5}
				source: 'Media/' + root.student_pic +'.jpg'
				allow_stretch: False
				radius: [40,40,40,40]
    MDLabel:
        text: ('[font=Fonts/Roboto-Black]STUDENT NUMBER[/font]')
        font_size: '15dp'
        markup: True
        halign: "center"
        theme_text_color: 'Custom'
        text_color: rgba('#07575B')
        pos_hint: {'center_x': 0.2, 'center_y' : 0.46}
    FloatLayout:
		pos_hint: {'center_y': 0.38, 'center_x': 0.2}
		size_hint: 0.20, 0.10
		canvas:
			Color:
				rgba: rgba('#61A4AD')
			RoundedRectangle:
                radius: [30,30,30,30]
				size: self.size
				pos: self.pos
		MDLabel:
			text: '[font=Fonts/Roboto-Black]' + root.student_number + '[/font]'
			font_size: '18dp'
			markup: True
			halign: "center"
			theme_text_color: 'Custom'
			text_color: rgba('#FFFFFF')
			pos_hint: {'center_x': 0.5, 'center_y' : 0.5}
    Image:
        pos_hint: {'center_x': 0.2, 'center_y' : 0.15}
        source: 'Media/QR_Attendance_Logo.png'
        size_hint_x: 0.125
        allow_stretch: False
	BoxLayout:
		pos_hint: {'center_y': 0.15, 'center_x': 0.2}
		size_hint: 0.05, 0.1
		canvas:
			Color:
				rgba: rgba('#FFFFFF')
			RoundedRectangle:
				radius: [10,10,10,10]
				size: self.size
				pos: self.pos
		ZBarCam:
			id: qrcodecam
