# forms the design and layout of login screen
<LoginScreen>:
	Widget:
		canvas:
			Color:
				rgba: rgba('#07575B')
			Rectangle:
				size: self.size
				pos: self.pos
	FloatLayout:
		pos_hint: {'center_y': 0.5, 'center_x': 0.85}
		size_hint: 0.30, 1
		canvas:
			Color:
				rgba: rgba('#E1E1E1')
			Rectangle:
				size: self.size
				pos: self.pos
        Image:
            pos_hint: {'center_x': 0.5, 'center_y' : 0.7}
            source: 'Media/QR_Attendance_Logo.png'
            size_hint_x: 0.5
            allow_stretch: False
		MDLabel:
            text: ('[font=Fonts/Roboto-Black]Quick Response (QR) Attendance[/font]')
            halign: 'center'
            font_size: '15dp'
            markup: True
			halign: "center"
			theme_text_color: 'Custom'
            text_color: rgba('#07575B')
            pos_hint: {'center_x': 0.5, 'center_y' : 0.55}
        FloatLayout:
            pos_hint: {'center_x': 0.5, 'center_y' : 0.5}
            size_hint: 0.45, 0.003
            canvas:
                Color:
                    rgba: rgba('#07575B')
                Rectangle:
                    size: self.size
                    pos: self.pos
		MDLabel:
            text: ('[font=Fonts/Roboto-Black]Email Address[/font]')
            halign: 'left'
            font_size: '10dp'
            markup: True
			halign: "left"
			theme_text_color: 'Custom'
            text_color: rgba('#07575B')
            pos_hint: {'center_x': 0.55, 'center_y' : 0.45}
		MDTextFieldRound:
			id: username
			hint_text: 'university.email@edu.ph'
			text_color: rgba('#07575B')
			size_hint: (0.75, None)
            font_size: "9.5dp"
			pos_hint: {'center_x' : 0.5, 'center_y' : 0.41}
			normal_color: rgba('#FFFFFF')
			color_active: rgba('#C0DEE5')
			line_color: rgba('#07575B')
			# icon_left: "email"
			# icon_left_color: rgba('#07575B')
		MDLabel:
            text: ('[font=Fonts/Roboto-Black]Password[/font]')
            halign: 'left'
            font_size: '10dp'
            markup: True
			halign: "left"
			theme_text_color: 'Custom'
            text_color: rgba('#07575B')
            pos_hint: {'center_x': 0.55, 'center_y' : 0.35}
		MDTextFieldRound:
			id: password
			hint_text: '***********************'
            password: True
			text_color: rgba('#07575B')
			size_hint: (0.75, None)
            font_size: "9.5dp"
			pos_hint: {'center_x' : 0.5, 'center_y' : 0.31}
			normal_color: rgba('#FFFFFF')
			color_active: rgba('#C0DEE5')
			line_color: rgba('#07575B')
			# icon_left: "lock"
			# icon_left_color: rgba('#07575B')
		MDFillRoundFlatButton:
			text: '[font=Fonts/Roboto-Bold][color=#FFFFFF]        SIGN IN        [/color][/font]'
			markup: True
			md_bg_color: rgba('#07575B')
            font_size: "10dp"
			pos_hint: {'center_x' : 0.5, 'center_y' : 0.22}
			# on_press:
			# 	root.do_login(username.text, password.text)
            #     username.text = ""
            #     password.text = ""
            #     root.manager.transition.direction = 'left'
            #     root.manager.transition.duration = .3
