# form the design and layout of the hamburger menu
<NavLayoutScreen>:
    MDNavigationLayout:
        id: navigation_layout
        ScreenManager:
            Screen:
                BoxLayout:
                    orientation: 'vertical'

                    MDToolbar:
                        id: toolbar
                        title: 'QR Attendance'
                        left_action_items: [["menu", lambda x: nav_drawer.set_state("open")]]
                        right_action_items: [["qrcode-scan", lambda x: root.activate_scanner()], ["clipboard-edit", lambda x: nav_drawer.set_state("open")]]
                        theme_text_color: 'Custom'
                        md_bg_color: rgba('#07575B')
                        elevation:5

                    ScreenManager:
                        id: manage

                        HomeScreen:
                            name: 'home_screen'

                        AboutScreen:
                            name: 'about_app'

                        HelpScreen:
                            name: 'help'

                        BlankScreen:
                            name: 'blank'

        MDNavigationDrawer:
            id: nav_drawer

            canvas:
                Color:
                    rgba: rgba('#FFFFFF')
                Rectangle:
                    pos: self.pos
                    size: self.size

            BoxLayout:
                orientation: 'vertical'
                padding: "8dp"
                spacing: "8dp"
                Image:
                    size_hint_y: .3
                    source: "Media/QR_Attendance_Logo.png"
                ScrollView:
                    MDList:
                        OneLineIconListItem:
                            text: "Home"
                            theme_text_color: 'Custom'
                            text_color: rgba('#07575B')
                            on_release:
                                app.show_screen("home_screen")
                                nav_drawer.set_state("close")
                            IconLeftWidget:
                                icon: "home"
                                theme_text_color: 'Custom'
                                text_color: rgba('#07575B')
                                on_release:
                                    app.show_screen("home_screen")
                                    nav_drawer.set_state("close")
                        OneLineIconListItem:
                            text: "About the app"
                            theme_text_color: 'Custom'
                            text_color: rgba('#07575B')
                            on_release:
                                app.show_screen("about_app")
                                nav_drawer.set_state("close")
                            IconLeftWidget:
                                icon: "card-bulleted-settings"
                                theme_text_color: 'Custom'
                                text_color: rgba('#07575B')
                                on_release:
                                    app.show_screen("about_app")
                                    nav_drawer.set_state("close")
                        OneLineIconListItem:
                            text: "Help"
                            theme_text_color: 'Custom'
                            text_color: rgba('#07575B')
                            on_release:
                                app.show_screen("help")
                                nav_drawer.set_state("close")
                            IconLeftWidget:
                                icon: "account-question"
                                theme_text_color: 'Custom'
                                text_color: rgba('#07575B')
                                on_release:
                                    app.show_screen("help")
                                    nav_drawer.set_state("close")
                        OneLineIconListItem:
                            text: "Logout"
                            theme_text_color: 'Custom'
                            text_color: rgba('#07575B')
                            on_release:
                                nav_drawer.set_state("close")
                                root.manager.current="login"
                                root.manager.transition.direction = 'right'
                                root.manager.transition.duration = .3
                            IconLeftWidget:
                                icon: "logout"
                                theme_text_color: 'Custom'
                                text_color: rgba('#07575B')
                                on_release:
                                    nav_drawer.set_state("close")
                                    root.manager.current="login"
                                    root.manager.transition.direction = 'right'
                                    root.manager.transition.duration = .3
